[theme]
# Primary accent color for interactive elements
primaryColor = "#1f77b4"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Max upload size in MB
maxUploadSize = 200

# Enable CORS
enableCORS = false

# Enable XSRF protection
enableXsrfProtection = true

[browser]
# Internet address where users should point their browsers to connect to the app
gatherUsageStats = false

[runner]
# Allows you to type a variable or string by itself in a single line of Python code to write it to the app
magicEnabled = true

# Install a Python tracer to allow you to stop or pause your script at any point and introspect it
fastReruns = true
